import type { Metadata } from "next";
import { siteConfig } from "./site";

/** OG image is generated by `src/app/opengraph-image.tsx`. */
const defaultOgImagePath = "/opengraph-image";

export function absoluteUrl(path: string): string {
  const base = siteConfig.url.replace(/\/$/, "");
  const p = path.startsWith("/") ? path : `/${path}`;
  return `${base}${p}`;
}

export function defaultOpenGraph(): NonNullable<Metadata["openGraph"]> {
  return {
    type: "website",
    locale: siteConfig.locale,
    siteName: siteConfig.name,
    images: [{ url: absoluteUrl(defaultOgImagePath), width: 1200, height: 630, alt: siteConfig.name }],
  };
}

export function pageMetadata(opts: {
  title: string;
  description: string;
  path: string;
  image?: string;
}): Metadata {
  const url = absoluteUrl(opts.path);
  return {
    title: opts.title,
    description: opts.description,
    alternates: { canonical: url },
    openGraph: {
      ...defaultOpenGraph(),
      title: opts.title,
      description: opts.description,
      url,
      images: opts.image
        ? [{ url: absoluteUrl(opts.image), width: 1200, height: 630, alt: opts.title }]
        : [{ url: absoluteUrl(defaultOgImagePath), width: 1200, height: 630, alt: opts.title }],
    },
    twitter: {
      card: "summary_large_image",
      title: opts.title,
      description: opts.description,
    },
  };
}
